# Generated by Django 4.0.2 on 2022-03-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sad',
            name='recipe_material',
        ),
        migrations.RemoveField(
            model_name='sad',
            name='recipe_type',
        ),
    ]
