# Generated by Django 4.0.2 on 2022-03-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_post_recipe_material_post_recipe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sad',
            name='recipe_material',
        ),
        migrations.RemoveField(
            model_name='sad',
            name='recipe_type',
        ),
    ]
