# Generated by Django 4.0.2 on 2022-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_remove_post_recipe_material_remove_post_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sad',
            name='recipe_material',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sad',
            name='recipe_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
